name: tabame
description: Tabame is a quick menu app.

publish_to: 'none'

version: 1.2.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  animated_button_bar: ^1.0.0
  characters: ^1.2.0
  contextual_menu: ^0.1.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.3
  ffi: ^2.0.0
  filepicker_windows: ^2.0.2
  fl_chart: ^0.70.0
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+3
  foldable_list: ^1.0.1
  http: ^1.2.2
  intl: ^0.20.1
  local_notifier: ^0.1.5
  math_parser: ^1.5.0
  screenshot: ^3.0.0
  tabamewin32:
    path: tabamewin32
  units_converter: ^3.0.2
  win32: ^5.9.0
  window_manager: ^0.4.3
  zoom_widget: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  msix: ^3.6.3

flutter:

  uses-material-design: true

  assets:
    # - resources/logo.png
    - resources/logo_light.png
    - resources/logo_dark.png
    - resources/wizzard1.png
    - resources/wizzard2.png
    - resources/wizzard3.png
    - resources/wizzard4.png
    - resources/gradient/
